Homework 02
VladimirSVS/python_base pull request #1
Opened 2021-10-12 20:06 UTC by VladimirSVS

Homework 02 done

2021-10-13 19:07 UTC, mahenzon requested changes
В целом нормально, нужно поправить странное решение с исключением, а также добавить new line at the end of some files

2021-10-13 19:07 UTC, mahenzon commented on homework_02/base.py
> +                raise
Зачем такая конструкция?

2021-10-13 19:07 UTC, mahenzon commented on homework_02/base.py
> +            raise
Тут тоже странно

2021-10-13 19:07 UTC, mahenzon commented on homework_02/plane.py
> +            raise
И тут не нужно ловить исключение и снова его выкидывать

2021-10-14 05:52 UTC, VladimirSVS commented on homework_02/base.py
> +                raise
Поправил

2021-10-14 05:52 UTC, VladimirSVS commented on homework_02/base.py
> +            raise
Поправил

2021-10-14 05:52 UTC, VladimirSVS commented on homework_02/plane.py
> +            raise
Поправил

2021-10-14 13:40 UTC, mahenzon approved these changes

2021-10-14 13:54 UTC, merged